/**
 * Worker entry (OpenNext custom worker): the generated app handler, plus the
 * Cron Trigger that runs the Top-up backfill every 5 minutes
 * (wrangler.jsonc `triggers.crons`, lib/scheduledBackfill.js).
 */
// .open-next/worker.js is generated by `opennextjs-cloudflare build`.
import handler from './.open-next/worker.js';
import { runScheduledBackfill } from './lib/scheduledBackfill.js';

export default {
    fetch: handler.fetch,

    async scheduled(event, env, ctx) {
        await runScheduledBackfill(handler.fetch, env, ctx);
    },
};
