/**
 * Worker entry (OpenNext custom worker): the generated app handler, plus the
 * Cron Triggers that run every 5 minutes (wrangler.jsonc `triggers.crons`):
 *   - the Top-up backfill (lib/scheduledBackfill.js)
 *   - the composite-job sweep (ADR-0029), via /api/admin/composite-redrive
 *   - the upload sweep (lib/uploadSweep.js), which deletes abandoned user
 *     sources from R2. Held to its own window rather than the asset default,
 *     because an upload is a third party's content (ADR-0025 section 8.1).
 *
 * They are independent: one failing must not stop another, so each is
 * settled separately rather than awaited in sequence.
 */
// .open-next/worker.js is generated by `opennextjs-cloudflare build`.
import handler from './.open-next/worker.js';
import { runScheduledBackfill } from './lib/scheduledBackfill.js';
import { sweepUploads } from './lib/uploadSweep.js';
import { isConfigured as r2IsConfigured } from './packages/adapters/r2.js';

export default {
    fetch: handler.fetch,

    async scheduled(event, env, ctx) {
        const results = await Promise.allSettled([
            runScheduledBackfill(handler.fetch, env, ctx),
            runScheduledBackfill(handler.fetch, env, ctx,
                { path: '/api/admin/composite-redrive', label: '[composite-redrive-cron]' }),
            runUploadSweep(env),
        ]);
        for (const r of results) {
            if (r.status === 'rejected') console.error('[cron] task threw:', r.reason && r.reason.message);
        }
    },
};

/**
 * The sweep reads R2 credentials from the Worker env rather than
 * process.env: a scheduled invocation has no request context, so the
 * adapter's own envConfig() cannot see the bindings.
 */
async function runUploadSweep(env) {
    const cfg = {
        accountId: env.R2_ACCOUNT_ID,
        accessKeyId: env.R2_ACCESS_KEY_ID,
        secretAccessKey: env.R2_SECRET_ACCESS_KEY,
        bucket: env.R2_BUCKET,
        jurisdiction: env.R2_JURISDICTION || undefined,
    };
    if (!r2IsConfigured(cfg)) {
        console.error('[upload-sweep] R2 not configured; skipping');
        return { ok: false };
    }
    const out = await sweepUploads(cfg);
    if (!out.ok) console.error('[upload-sweep] failed:', out.error);
    else if (out.deleted || out.failed) console.error('[upload-sweep]', JSON.stringify(out));
    return out;
}
