/**
 * Worker entry (OpenNext custom worker): the generated app handler, plus the
 * Cron Triggers that run every 5 minutes (wrangler.jsonc `triggers.crons`):
 *   - the Top-up backfill (lib/scheduledBackfill.js)
 *   - the Auto Short step sweep (lib/autoShortSweep.js), which re-reads
 *     pipeline steps a provider callback never finished
 *   - the upload sweep (lib/uploadSweep.js), which deletes abandoned user
 *     sources from R2, and the uploads of jobs that have finished. Held to its own window rather than the asset default,
 *     because an upload is a third party's content (ADR-0025 section 8.1).
 *
 * The tasks are independent: one failing must not stop the others, so each is
 * settled separately rather than awaited in sequence.
 */
// .open-next/worker.js is generated by `opennextjs-cloudflare build`.
import handler from './.open-next/worker.js';
import { runScheduledBackfill } from './lib/scheduledBackfill.js';
import { sweepUploads, sweepConsumedUploads } from './lib/uploadSweep.js';
import { isConfigured as r2IsConfigured } from './packages/adapters/r2.js';
import { sweepSteps } from './lib/autoShortSweep.js';
import { reapAssets } from './lib/assetReap.js';
import { runtimeDeps, runtimeKeys } from './lib/autoShortRuntime.js';

export default {
    fetch: handler.fetch,

    async scheduled(event, env, ctx) {
        const results = await Promise.allSettled([
            runScheduledBackfill(handler.fetch, env, ctx),
            runUploadSweep(env),
            runAutoShortSweep(env),
            runAssetReap(env),
        ]);
        for (const r of results) {
            if (r.status === 'rejected') console.error('[cron] task threw:', r.reason && r.reason.message);
        }
    },
};

/**
 * R2 objects that expire_assets (0016) queued when it deleted their rows.
 * Nothing drained this queue before, so the bytes outlived the account's
 * access to them and the 90-day promise in the privacy notice.
 */
async function runAssetReap(env) {
    const cfg = { supabaseUrl: env.SUPABASE_URL, serviceRoleKey: env.SUPABASE_SERVICE_ROLE_KEY };
    const r2cfg = r2EnvFrom(env);
    if (!cfg.supabaseUrl || !cfg.serviceRoleKey || !r2IsConfigured(r2cfg)) {
        console.error('[reap-assets] not configured; skipping');
        return { ok: false, skipped: 'not_configured' };
    }
    const out = await reapAssets(cfg, r2cfg);
    if (!out.ok) console.error('[reap-assets] failed:', out.error);
    else if (out.processed) console.error('[reap-assets]', JSON.stringify(out));
    return out;
}

/** Auto Short steps stuck past their provider's normal time (lib/autoShortSweep.js). */
async function runAutoShortSweep(env) {
    const keys = runtimeKeys(env);
    const cfg = { supabaseUrl: env.SUPABASE_URL, serviceRoleKey: env.SUPABASE_SERVICE_ROLE_KEY };
    const r2cfg = r2EnvFrom(env);
    if (!keys || !cfg.supabaseUrl || !cfg.serviceRoleKey || !env.PUBLIC_HOST || !r2IsConfigured(r2cfg)) {
        return { ok: false, skipped: 'not_configured' };
    }
    const deps = runtimeDeps({ cfg, r2cfg, publicHost: env.PUBLIC_HOST, ...keys });
    const out = await sweepSteps({ cfg, deps, falKey: keys.falKey, kieKey: keys.kieKey });
    if (out.checked) console.error('[auto-short-sweep]', JSON.stringify(out));
    return out;
}

function r2EnvFrom(env) {
    return {
        accountId: env.R2_ACCOUNT_ID,
        accessKeyId: env.R2_ACCESS_KEY_ID,
        secretAccessKey: env.R2_SECRET_ACCESS_KEY,
        bucket: env.R2_BUCKET,
        jurisdiction: env.R2_JURISDICTION || undefined,
    };
}

/**
 * The sweep reads R2 credentials from the Worker env rather than
 * process.env: a scheduled invocation has no request context, so the
 * adapter's own envConfig() cannot see the bindings.
 */
async function runUploadSweep(env) {
    const cfg = r2EnvFrom(env);
    if (!r2IsConfigured(cfg)) {
        console.error('[upload-sweep] R2 not configured; skipping');
        return { ok: false };
    }
    const out = await sweepUploads(cfg);
    if (!out.ok) console.error('[upload-sweep] failed:', out.error);
    else if (out.deleted || out.failed) console.error('[upload-sweep]', JSON.stringify(out));

    if (env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY) {
        const used = await sweepConsumedUploads(cfg, { supabaseUrl: env.SUPABASE_URL, serviceRoleKey: env.SUPABASE_SERVICE_ROLE_KEY });
        if (!used.ok) console.error('[upload-sweep] consumed pass failed:', used.error);
        else if (used.deleted || used.failed) console.error('[upload-sweep] consumed', JSON.stringify(used));
    } else {
        console.error('[upload-sweep] Supabase not configured; consumed uploads wait for the age sweep');
    }
    return out;
}
